[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$$2y$$05$$oUuwBi8930/w3OJBesBfweGVZE1D7N2m6zAE/tnnednojoz4KZ39O"
  ]

[http.routers.api]
  rule = "Host(`monitor.example.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
